[project]
name = "Proadv"
version = "0.0.1"
description = "An MLOps project for productionizing models"
authors = [{name = "Sai Sreenivas", email = "sreenivassaibks@gmail.com"}]

[tool.setuptools]
packages = {find = {}}

[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}